# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mod <- function(a, n) {
    .Call(`_NeverConsumersR_mod`, a, n)
}

gen_truncated_normals_never_c <- function(trunc_value, startxi, numgen) {
    .Call(`_NeverConsumersR_gen_truncated_normals_never_c`, trunc_value, startxi, numgen)
}

update_Ni_with_covariates_c <- function(Xtildei, beta, Utildei, alpha, GGalpha, n, mmi, didconsume) {
    .Call(`_NeverConsumersR_update_Ni_with_covariates_c`, Xtildei, beta, Utildei, alpha, GGalpha, n, mmi, didconsume)
}

gen_Wtildei_1foodplusenergy_never_c <- function(Wtildei, beta, Xtildei, Utildei, n, iSigmae, Wistar, mmi, numgen) {
    .Call(`_NeverConsumersR_gen_Wtildei_1foodplusenergy_never_c`, Wtildei, beta, Xtildei, Utildei, n, iSigmae, Wistar, mmi, numgen)
}

formGofSigmae_never_c <- function(r, theta, s22, s33, qq, mmi) {
    .Call(`_NeverConsumersR_formGofSigmae_never_c`, r, theta, s22, s33, qq, mmi)
}

updated_parameter_r_never_c <- function(r, theta, s22, s33, qq, mmi, n) {
    .Call(`_NeverConsumersR_updated_parameter_r_never_c`, r, theta, s22, s33, qq, mmi, n)
}

updated_parameter_s22_never_c <- function(r, theta, s22, s33, qq, mmi, n) {
    .Call(`_NeverConsumersR_updated_parameter_s22_never_c`, r, theta, s22, s33, qq, mmi, n)
}

updated_parameter_s33_never_c <- function(r, theta, s22, s33, qq, mmi, n) {
    .Call(`_NeverConsumersR_updated_parameter_s33_never_c`, r, theta, s22, s33, qq, mmi, n)
}

updated_parameter_theta_never_c <- function(r, theta, s22, s33, qq, mmi) {
    .Call(`_NeverConsumersR_updated_parameter_theta_never_c`, r, theta, s22, s33, qq, mmi)
}

update_iSigmau_c <- function(Sigmau, prior_Sigmau_doff, prior_Sigmau_mean, Utildei, n, jjMCMC) {
    .Call(`_NeverConsumersR_update_iSigmau_c`, Sigmau, prior_Sigmau_doff, prior_Sigmau_mean, Utildei, n, jjMCMC)
}

update_Utildei_c <- function(Utildei, beta, Wtildei, iSigmae, Ni, isnever, didconsume, Xtildei, mmi, iSigmau, n) {
    .Call(`_NeverConsumersR_update_Utildei_c`, Utildei, beta, Wtildei, iSigmae, Ni, isnever, didconsume, Xtildei, mmi, iSigmau, n)
}

update_beta1_with_prior_mean_random_walk_c <- function(Xtildei, mmi, prior_beta_mean, prior_beta_cov, beta, Wtildei, Utildei, iSigmae, isnever, update_beta1_var_ind) {
    .Call(`_NeverConsumersR_update_beta1_with_prior_mean_random_walk_c`, Xtildei, mmi, prior_beta_mean, prior_beta_cov, beta, Wtildei, Utildei, iSigmae, isnever, update_beta1_var_ind)
}

update_beta1_with_prior_mean_c <- function(Xtildei, mmi, prior_beta_mean, prior_beta_cov, beta, Wtildei, Utildei, iSigmae, isnever, update_beta1_var_ind) {
    .Call(`_NeverConsumersR_update_beta1_with_prior_mean_c`, Xtildei, mmi, prior_beta_mean, prior_beta_cov, beta, Wtildei, Utildei, iSigmae, isnever, update_beta1_var_ind)
}

update_beta2_with_prior_mean_c <- function(Xtildei, mmi, prior_beta_mean, prior_beta_cov, beta, Wtildei, Utildei, iSigmae) {
    .Call(`_NeverConsumersR_update_beta2_with_prior_mean_c`, Xtildei, mmi, prior_beta_mean, prior_beta_cov, beta, Wtildei, Utildei, iSigmae)
}

update_beta3_with_prior_mean_c <- function(Xtildei, mmi, prior_beta_mean, prior_beta_cov, beta, Wtildei, Utildei, iSigmae) {
    .Call(`_NeverConsumersR_update_beta3_with_prior_mean_c`, Xtildei, mmi, prior_beta_mean, prior_beta_cov, beta, Wtildei, Utildei, iSigmae)
}

rcpparma_hello_world <- function() {
    .Call(`_NeverConsumersR_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_NeverConsumersR_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_NeverConsumersR_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_NeverConsumersR_rcpparma_bothproducts`, x)
}

